FROM ubuntu:latest

WORKDIR /plan9port
RUN apt update
RUN apt install -y git make gcc libc-dev linux-headers-5.3.0-51-generic

RUN git clone --depth 1 https://github.com/9fans/plan9port.git .
RUN ./INSTALL
